import { TournamentTemplate, TemplateCategory } from '@/app/types/tournament-templates';

export const tournamentTemplates: TournamentTemplate[] = [
  {
    id: 'quick-match',
    name: 'Quick Match',
    description: 'Fast-paced 8-player tournament, perfect for quick games',
    icon: '⚡',
    category: 'quick',
    settings: {
      format: 'single-elimination',
      playerType: 'solo',
      minPlayers: 4,
      maxPlayers: 8,
      matchFormat: 'best-of-1',
      isPublic: true,
      allowSpectators: true,
      requireApproval: false,
      enableChat: true,
      enableScheduling: false,
      prizePoolEnabled: false,
      streamingEnabled: false,
      estimatedDuration: '1-2 hours',
    },
  },
  {
    id: 'weekend-warrior',
    name: 'Weekend Warrior',
    description: '16-player competitive tournament with best-of-3 matches',
    icon: '🎯',
    category: 'competitive',
    settings: {
      format: 'single-elimination',
      playerType: 'solo',
      minPlayers: 8,
      maxPlayers: 16,
      matchFormat: 'best-of-3',
      isPublic: true,
      allowSpectators: true,
      requireApproval: true,
      enableChat: true,
      enableScheduling: true,
      prizePoolEnabled: true,
      streamingEnabled: true,
      estimatedDuration: '3-5 hours',
    },
    scheduling: {
      allowTimeSlots: true,
      matchDuration: 45,
      breakBetweenMatches: 15,
    },
  },
  {
    id: 'pro-league',
    name: 'Pro League',
    description: '32-player professional tournament with strict scheduling',
    icon: '👑',
    category: 'championship',
    settings: {
      format: 'double-elimination',
      playerType: 'solo',
      minPlayers: 16,
      maxPlayers: 32,
      matchFormat: 'best-of-5',
      isPublic: true,
      allowSpectators: true,
      requireApproval: true,
      enableChat: true,
      enableScheduling: true,
      prizePoolEnabled: true,
      streamingEnabled: true,
      estimatedDuration: '6-8 hours',
    },
    scheduling: {
      allowTimeSlots: true,
      matchDuration: 60,
      breakBetweenMatches: 20,
    },
  },
  {
    id: 'casual-fun',
    name: 'Casual Fun',
    description: 'Relaxed tournament for friends and casual players',
    icon: '🎮',
    category: 'casual',
    settings: {
      format: 'single-elimination',
      playerType: 'solo',
      minPlayers: 4,
      maxPlayers: 16,
      matchFormat: 'best-of-1',
      isPublic: false,
      allowSpectators: true,
      requireApproval: false,
      enableChat: true,
      enableScheduling: false,
      prizePoolEnabled: false,
      streamingEnabled: false,
      estimatedDuration: '2-3 hours',
    },
  },
  {
    id: 'grand-championship',
    name: 'Grand Championship',
    description: '64-player major tournament with double elimination',
    icon: '🏆',
    category: 'championship',
    settings: {
      format: 'double-elimination',
      playerType: 'solo',
      minPlayers: 32,
      maxPlayers: 64,
      matchFormat: 'best-of-5',
      isPublic: true,
      allowSpectators: true,
      requireApproval: true,
      enableChat: true,
      enableScheduling: true,
      prizePoolEnabled: true,
      streamingEnabled: true,
      estimatedDuration: '2-3 days',
    },
    scheduling: {
      allowTimeSlots: true,
      matchDuration: 90,
      breakBetweenMatches: 30,
    },
  },
  {
    id: 'team-battle',
    name: 'Team Battle',
    description: '8 teams competing in coordinated team matches',
    icon: '🛡️',
    category: 'competitive',
    settings: {
      format: 'single-elimination',
      playerType: 'team',
      minPlayers: 4,
      maxPlayers: 8,
      matchFormat: 'best-of-3',
      teamSize: 4,
      isPublic: true,
      allowSpectators: true,
      requireApproval: true,
      enableChat: true,
      enableScheduling: true,
      prizePoolEnabled: true,
      streamingEnabled: true,
      estimatedDuration: '4-6 hours',
    },
    scheduling: {
      allowTimeSlots: true,
      matchDuration: 60,
      breakBetweenMatches: 15,
    },
  },
  {
    id: 'free-fire-tournament',
    name: 'Free Fire Tournament',
    description: 'Battle Royale tournament optimized for Free Fire',
    icon: '🔥',
    category: 'competitive',
    settings: {
      format: 'single-elimination',
      playerType: 'team',
      minPlayers: 8,
      maxPlayers: 16,
      matchFormat: 'best-of-3',
      teamSize: 4,
      isPublic: true,
      allowSpectators: true,
      requireApproval: true,
      enableChat: true,
      enableScheduling: true,
      prizePoolEnabled: true,
      streamingEnabled: true,
      estimatedDuration: '3-4 hours',
    },
    gamePresets: {
      game: 'Free Fire',
      rules: [
        'No hacking or third-party software',
        'Custom room codes will be shared 15 minutes before match',
        'Screenshot proof required for disputes',
        'Teams must have registered roster',
      ],
      mapPool: ['Bermuda', 'Purgatory', 'Kalahari'],
    },
    scheduling: {
      allowTimeSlots: true,
      matchDuration: 30,
      breakBetweenMatches: 10,
    },
  },
  {
    id: 'swiss-system',
    name: 'Swiss System',
    description: 'Fair matchmaking tournament where players face opponents with similar records',
    icon: '⚖️',
    category: 'competitive',
    settings: {
      format: 'swiss',
      playerType: 'solo',
      minPlayers: 8,
      maxPlayers: 32,
      matchFormat: 'best-of-3',
      isPublic: true,
      allowSpectators: true,
      requireApproval: true,
      enableChat: true,
      enableScheduling: true,
      prizePoolEnabled: true,
      streamingEnabled: true,
      estimatedDuration: '5-7 hours',
    },
    scheduling: {
      allowTimeSlots: true,
      matchDuration: 45,
      breakBetweenMatches: 15,
    },
  },
  {
    id: 'custom',
    name: 'Custom Tournament',
    description: 'Create your own tournament from scratch with full customization',
    icon: '⚙️',
    category: 'custom',
    settings: {
      format: 'single-elimination',
      playerType: 'solo',
      minPlayers: 4,
      maxPlayers: 64,
      matchFormat: 'best-of-1',
      isPublic: true,
      allowSpectators: true,
      requireApproval: false,
      enableChat: true,
      enableScheduling: false,
      prizePoolEnabled: false,
      streamingEnabled: false,
      estimatedDuration: 'Variable',
    },
  },
];

export const templateCategories: TemplateCategory[] = [
  {
    id: 'quick',
    name: 'Quick Play',
    description: 'Fast tournaments for immediate action',
    templates: tournamentTemplates.filter((t) => t.category === 'quick'),
  },
  {
    id: 'competitive',
    name: 'Competitive',
    description: 'Serious tournaments with skilled matchmaking',
    templates: tournamentTemplates.filter((t) => t.category === 'competitive'),
  },
  {
    id: 'casual',
    name: 'Casual',
    description: 'Relaxed tournaments for fun',
    templates: tournamentTemplates.filter((t) => t.category === 'casual'),
  },
  {
    id: 'championship',
    name: 'Championship',
    description: 'Major tournaments with prizes',
    templates: tournamentTemplates.filter((t) => t.category === 'championship'),
  },
  {
    id: 'custom',
    name: 'Custom',
    description: 'Build your own tournament',
    templates: tournamentTemplates.filter((t) => t.category === 'custom'),
  },
];

export function getTemplateById(id: string): TournamentTemplate | undefined {
  return tournamentTemplates.find((template) => template.id === id);
}

export function getTemplatesByCategory(category: string): TournamentTemplate[] {
  return tournamentTemplates.filter((template) => template.category === category);
}
